"""Add is_read to Message model

Revision ID: 880cde487140
Revises: 3e0e781efaa2
Create Date: 2025-06-19 16:16:39.072772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880cde487140'
down_revision = '3e0e781efaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column, allowing NULLs for now
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    # Step 2: Update existing rows to have a default value (e.g., true, assuming old messages are read)
    op.execute('UPDATE messages SET is_read = true WHERE is_read IS NULL')

    # Step 3: Alter the column to be NOT NULL
    op.alter_column('messages', 'is_read', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
