"""empty message

Revision ID: e9f553e1ebf6
Revises: 1dffc659eeb6
Create Date: 2025-06-19 17:18:52.847869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f553e1ebf6'
down_revision = '1dffc659eeb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'chats', ['chat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
